# 로컬 환경에서 사용하는 설정
spring:
  # 로컬 DB 접속 정보 (MySQL 사용)
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}

logging:
  level:
    org.springframework.security: ${LOG_LEVEL_SECURITY:DEBUG}
    org.hibernate.SQL: ${LOG_LEVEL_HIBERNATE_SQL:DEBUG}
openai:
    api-key: ${OPENAI_API_KEY}
    api-url: ${OPENAI_API_URL:https://api.openai.com/v1/chat/completions}
    model: ${OPENAI_MODEL:gpt-4o-mini}